### ISSUE TITLE
openapi example fails to compile with spring-web 0.4.16 (Handler trait not implemented)

### ISSUE THREAD

**Issue by martindotpy** [spring-rs/spring-rs#211]
First of all, thank you very much for this project. The design and overall developer experience are excellent.

I tried running the example at
https://github.com/spring-rs/spring-rs/tree/master/examples/openapi-example.

using the following `Cargo.toml`:

```toml
[package]
name = "openapi-example"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
schemars = "1.2.1"
serde = "1.0.228"
spring = "0.4.8"
spring-sqlx = { version = "0.4.2", features = ["sqlite"] }
spring-web = { version = "0.4.16", features = [
    "openapi",
    "openapi-scalar",
] }
thiserror = "2.0.18"
tokio = { version = "1.49.0", features = ["full"] }
```

and the following `app.toml`:

```toml
[web]
port = 8000
graceful = true

[web.openapi]
doc_prefix = "/docs"
info = { title = "spring-web openapi example document", version = "0.0.1" }

[web.middlewares]
static = { enable = true }
compression = { enable = true }
logger = { enable = true, level = "warn" }
catch_panic = { enable = true }
timeout_request = { enable = true, timeout = 30000 }
cors = { enable = true, allow_origins = [
    "*",
], allow_headers = [
    "Authentication",
], allow_methods = [
    "GET",
    "POST",
], max_age = 60 }


[sqlx]
uri = "sqlite://db.sqlite?mode=rwc"
```

However, compilation fails with the following error:

```plaintext
error[E0277]: the trait bound `fn(spring_web::extractor::Path<u32>) -> impl Future<Output = Result<spring_web::extractor::Json<UserInfo>, ApiErrors>> {user_info_api}: Handler<_, _>` is not satisfied
    --> src/main.rs:112:10
     |
 111 | #[get_api("/user-info/{id}")]
     | ----------------------------- required by a bound introduced by this call
 112 | async fn user_info_api(Path(id): Path<u32>) -> Result<Json<UserInfo>, ApiErrors> {
     |          ^^^^^^^^^^^^^ the trait `Handler<_, _>` is not implemented for fn item `fn(spring_web::extractor::Path<u32>) -> impl Future<Output = Result<spring_web::extractor::Json<UserInfo>, ApiErrors>> {user_info_api}`
     |
     = note: Consider using `#[axum::debug_handler]` to improve the error message
help: the following other types implement trait `Handler<T, S>`
    --> /Users/alexr/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/axum-0.8.8/src/routing/method_routing.rs:1309:1
     |
1309 | / impl<S> Handler<(), S> for MethodRouter<S>
1310 | | where
1311 | |     S: Clone + 'static,
     | |_______________________^ `MethodRouter<S>` implements `Handler<(), S>`
     |
    ::: /Users/alexr/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/axum-0.8.8/src/handler/mod.rs:313:1
     |
 313 | / impl<H, S, T, L> Handler<T, S> for Layered<L, H, T, S>
 314 | | where
 315 | |     L: Layer<HandlerService<H, T, S>> + Clone + Send + Sync + 'static,
 316 | |     H: Handler<T, S>,
...    |
 320 | |     T: 'static,
 321 | |     S: 'static,
     | |_______________^ `Layered<L, H, T, S>` implements `Handler<T, S>`
note: required by a bound in `MethodRouter::<S>::on`
    --> /Users/alexr/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/axum-0.8.8/src/routing/method_routing.rs:633:12
     |
 631 |     pub fn on<H, T>(self, filter: MethodFilter, handler: H) -> Self
     |            -- required by a bound in this associated function
 632 |     where
 633 |         H: Handler<T, S>,
     |            ^^^^^^^^^^^^^ required by this bound in `MethodRouter::<S>::on`

For more information about this error, try `rustc --explain E0277`.
error: could not compile `openapi-example` (bin "openapi-example") due to 1 previous error
```

Interestingly, this error does not occur when cloning the repository directly and running the example from there (with the sqlite configuration changes).

Thanks again for the amazing project and your hard work!
